### ISSUE TITLE
Miner 1.1.15/1.1.16.rc1 setup failed after HA Core update

### ISSUE THREAD

**Issue by monkeyjpg** [Schnitzel/hass-miner#393]
## Version of the custom_component

Found at 1.1.15 and 1.1.16.rc1

## Configuration

Core
2024.10.0
Supervisor
2024.09.1
Operating System
13.1
User interface
20241002.2

## Debug log

homeassistant.setup
Source: setup.py:269
Setup failed for custom integration 'miner': Requirements for miner not found: ['pyasic==0.60.7'].

-------

homeassistant.util.package
Source: util/package.py:150

Unable to install package pyasic==0.60.6: × No solution found when resolving dependencies: ╰─▶ Because there is no version of betterproto==2.0.0b6 and pyasic==0.60.6 depends on betterproto==2.0.0b6, we can conclude that pyasic==0.60.6 cannot be used. And because you require pyasic==0.60.6, we can conclude that your requirements are unsatisfiable. hint: betterproto was requested with a pre-release marker (e.g., betterproto==2.0.0b6), but pre-releases weren't enabled (try: `--prerelease=allow`)

**Comment by maxxe39** [comment]
Same Problem

**Comment by msmitka** [comment]
Same problem
Setup failed for custom integration 'miner': Requirements for miner not found: ['pyasic==0.60.6'].

**Comment by ThorPrez** [comment]
In my case the log entry is `Setup failed for custom integration 'miner': Requirements for miner not found: ['pyasic==0.60.5'].`
Both miner were running with 1.1.14 before, but with last HA update not anymore. Also not running with 1.1.16.rc1.

**Comment by Ben-in-Chicago** [comment]
I was going to open an issue for this as well. Latest HA Core update and pre-release miner version:

![image](https://github.com/user-attachments/assets/153ea840-4b11-4ad2-959a-9250473c0c0c)

**Comment by b-rowan** [comment]
Ah.  Betterproto being stupid.  That's not great, as I'm not sure the existing BOS+ schema actually complies with what betterproto wants.

**Comment by b-rowan** [comment]
"Betterproto was requested with a pre-release marker, but pre-releases were not enabled..."

**Comment by Ben-in-Chicago** [comment]
> "Betterproto was requested with a pre-release marker, but pre-releases were not enabled..."

I'm running HA Green so not really sure how to alter the code to enable pre-releases. I know others here are smart enough to figure this out. :)

**Comment by Tanki90** [comment]
same problem

**Comment by b-rowan** [comment]
> > "Betterproto was requested with a pre-release marker, but pre-releases were not enabled..."
> 
> 
> 
> I'm running HA Green so not really sure how to alter the code to enable pre-releases. I know others here are smart enough to figure this out. :)

I'll have to try to out on my instance when I get home, the good news is it's a HASS change, but I don't know how to deal with it or really what the did.

**Comment by gmint** [comment]
Same here.

**Comment by ngluvakov** [comment]
I have the same problem. Please fix it.

**Comment by jax24fr** [comment]
Same here my friend.
Can you please try to fix it. Thanks !

**Comment by b-rowan** [comment]
I have asked the home assistant team about it, but it's an issue with home assistant, not this repo.

**Comment by ThorPrez** [comment]
With version 1.1.12 on HA Core 2024.9.3 it´s runningwithout any problems.
If neccessary I can test the upcoming versions to see if it´s HA oder miner.

**Comment by dennisreimann** [comment]
@ThorPrez Thanks for the pointer. I downgraded HA Core using the Terminal (`ha core update --version 2024.9.3`) and now Miner 1.1.16rc1 is working for me again.

**Comment by xmike13** [comment]
> Same Problem

**Comment by Schelin78** [comment]
Logger: homeassistant.setup
Källa: setup.py:269
Inträffade först: 10:05:57 (1 händelser)
Senast loggade: 10:05:57

Setup failed for custom integration 'miner': Requirements for miner not found: ['pyasic==0.60.6'].

**Comment by ThorPrez** [comment]
Guys, downgrade HA core to 2024.9.3 and it will work.

**Comment by xmike13** [comment]
Yes, downgrade worked also for me

**Comment by brtwrs** [comment]
Im running 2014.10.1 installed de missing package by hand in HA core (pip install pyasic). Restart HA and you're good to go with the latest HA version

**Comment by Ben-in-Chicago** [comment]
> pip install pyasic

Hello! I'm using HA Green. Would you happen to know how I could do that? Here is what I get when I tried within the terminal app:

![image](https://github.com/user-attachments/assets/ef047b44-7339-4265-8cd9-7cf1e5f2f34f)

**Comment by b-rowan** [comment]
@Ben-in-Chicago try `python3 -m pip install pyasic`

**Comment by Ben-in-Chicago** [comment]
> python3 -m pip install pyasic

![image](https://github.com/user-attachments/assets/219d4925-0e6d-4546-bef6-0fc8c0472c71)

**Comment by b-rowan** [comment]
> > python3 -m pip install pyasic
> 
> ![image](https://private-user-images.githubusercontent.com/99691112/374301556-219d4925-0e6d-4546-bef6-0fc8c0472c71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMjkyMzIsIm5iZiI6MTcyODMyODkzMiwicGF0aCI6Ii85OTY5MTExMi8zNzQzMDE1NTYtMjE5ZDQ5MjUtMGU2ZC00NTQ2LWJlZjYtMGZjOGMwNDcyYzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDE5MjIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNjY3MDMyZTVkNjE4ZDQ3OTc0ZmMzNjM4ZWRiZDdlOWQ3MzUxOTNiMTY2OGQyNjQ4YTVjODZlNmY5ODZlZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Re5X2A0VGlFv6_8QEHrZT8Fxqx6oQpvfPjTT8jJ-pms)

`python` rather than` python3`?

**Comment by Ben-in-Chicago** [comment]
> > > python3 -m pip install pyasic
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/99691112/374301556-219d4925-0e6d-4546-bef6-0fc8c0472c71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMjkyMzIsIm5iZiI6MTcyODMyODkzMiwicGF0aCI6Ii85OTY5MTExMi8zNzQzMDE1NTYtMjE5ZDQ5MjUtMGU2ZC00NTQ2LWJlZjYtMGZjOGMwNDcyYzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDE5MjIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNjY3MDMyZTVkNjE4ZDQ3OTc0ZmMzNjM4ZWRiZDdlOWQ3MzUxOTNiMTY2OGQyNjQ4YTVjODZlNmY5ODZlZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Re5X2A0VGlFv6_8QEHrZT8Fxqx6oQpvfPjTT8jJ-pms)
> 
> `python` rather than `python3`?

Same result

**Comment by brtwrs** [comment]
Not exactly sure how to do that on the green. I run HA in a docker container and just exec into the container. Make sure you are in the Linux cli not the HA cli

**Comment by msmitka** [comment]
Can't the repair be a downgrade???

**Comment by b-rowan** [comment]
> Can't the repair be a downgrade???
> 
> You are not serious.

It's an issue with home assistant, and until they reply to me on the posts I've made, I can't do anything about it.

**Comment by ngluvakov** [comment]
> > Can't the repair be a downgrade???
> > You are not serious.
> 
> It's an issue with home assistant, and until they reply to me on the posts I've made, I can't do anything about it.

Thank you for working on it. You sir, are a gentleman and a scholar. You have my respect.

**Comment by editwentyone** [comment]
login with ssh, enter docker `docker exec -it homeassistant bash`
`pip install pyasic==0.60.7`
install / update  `v1.1.16rc1` with HACS
works on `core 2024.10.1`

**Comment by maxxe39** [comment]
> login with ssh, enter docker `docker exec -it homeassistant bash` `pip install pyasic==0.60.7` install / update `v1.1.16rc1` with HACS works on `core 2024.10.1`

Can I do this with the Terminal?
The commands dont work. Maybe i am not a pro at this point..

**Comment by b-rowan** [comment]
> > login with ssh, enter docker `docker exec -it homeassistant bash` `pip install pyasic==0.60.7` install / update `v1.1.16rc1` with HACS works on `core 2024.10.1`
> 
> 
> 
> Can I do this with the Terminal?
> 
> The commands dont work. Maybe i am not a pro at this point..

This will only work if you're running home assistant with docker.

User the Terminal and SSH add-on to get ssh access, the run the commands past the docker command.  The `docker exec ...` command is the docker deployment version of SSH.

**Comment by spamferkel** [comment]
> login with ssh, enter docker `docker exec -it homeassistant bash` `pip install pyasic==0.60.7` install / update `v1.1.16rc1` with HACS works on `core 2024.10.1`

2024.10.2 also confirmed working

**Comment by b-rowan** [comment]
> > login with ssh, enter docker `docker exec -it homeassistant bash` `pip install pyasic==0.60.7` install / update `v1.1.16rc1` with HACS works on `core 2024.10.1`
> 
> 
> 
> 2024.10.2 also confirmed working

Fixed in latest version of home assistant then.  Nice.

**Comment by tim-brand** [comment]
Are you sure this is fixed? I still have the error. Maybe you installed the dependency manually, which fixed it for you?

I'm running haos and just updated HA to 2024.10.2, and still get the same error when trying to add a miner. 
I tried v1.1.16rc1:
```
homeassistant.requirements.RequirementsNotFound: Requirements for miner not found: ['pyasic==0.60.7'].
```
But also tried v1.1.15
```
homeassistant.requirements.RequirementsNotFound: Requirements for miner not found: ['pyasic==0.60.6'].
```

**Comment by b-rowan** [comment]
Yeah, like I said, it's actually an issue with home assistant, nothing has changed on the pyasic side that would cause it to be unable to install.

**Comment by b-rowan** [comment]
> Can you please post a link to your posts. I would like to join the discussion an support you.

@spamferkel 

https://community.home-assistant.io/t/home-assistant-24-10-0-issues-with-beta-package-versions/778656

**Comment by tim-brand** [comment]
> Yeah, like I said, it's actually an issue with home assistant, nothing has changed on the pyasic side that would cause it to be unable to install.

I get that, but I think it's not fixed with the latest HA release. At least I can't confirm it.

**Comment by b-rowan** [comment]
> My guess would be that the fix would come with Home Assistant Operating System update and not with a new version of Home Assistant, since pyasic would be part of the OS and not of HA

Not so sure about this, because the issue isn't actually with any dependency per-se, but with the way home assistant is installing dependencies.  They need to allow pre-release dependencies, which needs to be changed in core AFAIU.

**Comment by ngluvakov** [comment]
Any news on the subject? Will the next version of this integration be able to work without any additional work?

**Comment by b-rowan** [comment]
> Any news on the subject? Will the next version of this integration be able to work without any additional work?

Still waiting on a response from the devs.  This is an issue with home assistant, not with this integration.

**Comment by b-rowan** [comment]
Opened an issue on core, we shall see if that gets any response.

**Comment by Ben-in-Chicago** [comment]
> login with ssh, enter docker `docker exec -it homeassistant bash` `pip install pyasic==0.60.7` install / update `v1.1.16rc1` with HACS works on `core 2024.10.1`

Seems I'm limited to the commands listed [here](https://www.home-assistant.io/common-tasks/os#home-assistant-via-the-command-line). Any other suggestions?

**Comment by spamferkel** [comment]
> > login with ssh, enter docker `docker exec -it homeassistant bash` `pip install pyasic==0.60.7` install / update `v1.1.16rc1` with HACS works on `core 2024.10.1`
> 
> Seems I'm limited to the commands listed [here](https://www.home-assistant.io/common-tasks/os#home-assistant-via-the-command-line). Any other suggestions?

You need to get root-access. Look here https://developers.home-assistant.io/docs/operating-system/debugging/ . Be very careful with this. You can easily destroy your homeassistant. This is normally just for devs and die-hard-linux-nerds ;) . If you can execute a command like `docker ps` you should get a list of running containers. Then you're on the right way and can go on with the commands you mentioned...

**Comment by Ben-in-Chicago** [comment]
> > > login with ssh, enter docker `docker exec -it homeassistant bash` `pip install pyasic==0.60.7` install / update `v1.1.16rc1` with HACS works on `core 2024.10.1`
> > 
> > 
> > Seems I'm limited to the commands listed [here](https://www.home-assistant.io/common-tasks/os#home-assistant-via-the-command-line). Any other suggestions?
> 
> You need to get root-access. Look here https://developers.home-assistant.io/docs/operating-system/debugging/ . Be very careful with this. You can easily destroy your homeassistant. This is normally just for devs and die-hard-linux-nerds ;) . If you can execute a command like `docker ps` you should get a list of running containers. Then you're on the right way and can go on with the commands you mentioned...

It appears limited to what I can do (within the GUI and my skillset) so it seems like I need to sit tight until this is resolved by the appropriate people.

![image](https://github.com/user-attachments/assets/9178e1d7-ec0f-477f-b50f-c167702310ec)

**Comment by ngluvakov** [comment]
This question makes me uneducated, but it is simple in other integrations - I install them, and they work. Is there a way for the developers to adapt the integration to the new system somehow?

**Comment by b-rowan** [comment]
> This question makes me uneducated, but it is simple in other integrations - I install them, and they work. Is there a way for the developers to adapt the integration to the new system somehow? 

The reason for this is because pyasic requires betterproto for managing BOS+ devices, because it's basically the only reasonable library for handling gRPC calls.  The problem is it has been in a beta version for about 2 years, and now home assistant is refusing to install it (probably because one flag needs to be set in their package manager, uv), which they updated from like 0.2.x to 0.4.x in 24.10.0.  Hence broken package, and I can't do anything about it since it is required for the integration to function at all.

**Comment by ngluvakov** [comment]
> > This question makes me uneducated, but it is simple in other integrations - I install them, and they work. Is there a way for the developers to adapt the integration to the new system somehow?
> 
> The reason for this is because pyasic requires betterproto for managing BOS+ devices, because it's basically the only reasonable library for handling gRPC calls. The problem is it has been in a beta version for about 2 years, and now home assistant is refusing to install it (probably because one flag needs to be set in their package manager, uv), which they updated from like 0.2.x to 0.4.x in 24.10.0. Hence broken package, and I can't do anything about it since it is required for the integration to function at all.

Thank you for letting us know. We live in the hope of having this resolved. :)

**Comment by Schnitzel** [comment]
Hey everyone

We fully understand the frustration of this, as @b-rowan said, this is a problem of homeassistant `2024.10.1` where the developers of homeassistant decided to not allow beta versions of specific python packages. hass-miner relies on pyasic (maintained by @b-rowan - so we would have control over this) which [itself relies on betterproto](https://github.com/UpstreamData/pyasic/blob/2b00e741caeed0ba1e617206c885ee0a65ef90e7/pyproject.toml#L18. No unfortunately the developer of beterproto only is [releasing beta versions](https://pypi.org/project/betterproto/#history). So far this was not a problem, but since homeassistant now does not allow beta versions anymore (reasons currently unclear) we cannot install pyasic anymore, which also means hass-miner doesn't work anymore.

Fixes & Workarounds

- The best possible fix is to have the homeassistant developers allow beta versions again - something which we trying to work with them here: https://github.com/home-assistant/core/issues/128981 if you want to help us, please comment on that issue that this is affecting you, the more people we have that report this affecting them the better.
- The second fix is to force homeassistant to install pyasic manually (`docker exec -it homeassistant bash` and `pip install pyasic==0.60.7`) this works via only if you run homeassistant via docker and not if you have homeassistant running on a raspberry pi or any other standalone server - as there you cannot just connect to core and update packages.
- A solution for any standalone server & raspberry pi users: Open the Terminal in the HomeAssistant UI and run `ha core update --version 2024.9.3` - this will downgrade (!) your homeassistant to a version were we can still install beta versions. Keep in mind though that downgrading of homeassistant isn't usually something that is suggested as it could cause other issues, but in this specific case it seems to be the best solution.

As soon as we have a solution from the homeassistant devs we will then hopefully be able to upgrade again to 2024.10.x or newer.

**Comment by smharm13** [comment]
Downgrading to 9.3 worked for me. Thank you all for you work on this and for continuing to push for a permanent fix.

**Comment by saxtron3000** [comment]
Running HACS on UmbrelOS (so Docker) and not able to use anu of the work arounds. 

Can any one list the commands to downgrade from terminal in Umbrel, please?

**Comment by Schnitzel** [comment]
@saxtron3000 unfortunately I don't have an UmbrelOS around to test, but I assume there is a way to connect into the homeassistant container in Umbrel? there you should be able to run `pip install pyasic==0.60.7` to fix this.

**Comment by b-rowan** [comment]
Is someone able to test out `v1.1.17rc`?  I tried putting the flag for `--prerelease-allow` into the manifest for that version after looking at how the install is done.

**Comment by brtwrs** [comment]
![Screenshot 2024-10-29 at 15 44 34](https://github.com/user-attachments/assets/4d52f631-87a4-428e-83df-fc5466ce721e)

Just tested it and its not working. Even when I manual install the package I still get the same error

**Comment by saxtron3000** [comment]
> @saxtron3000 unfortunately I don't have an UmbrelOS around to test, but I assume there is a way to connect into the homeassistant container in Umbrel? there you should be able to run `pip install pyasic==0.60.7` to fix this.

I run the pip install in the docker terminal and still get the same error:-

_Error

Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble_

**Comment by b-rowan** [comment]
I've opened a PR on core that should fix this, https://github.com/home-assistant/core/pull/129641.

**Comment by ngluvakov** [comment]
> Looks like they added it to the `2024.11.0` milestone, meaning this should (hopefully) be fixed in the next release of home assistant.

I installed the new release today, reinstalled the integration and still no luck. I begin to think there is no solution to this.

**Comment by b-rowan** [comment]
> > Looks like they added it to the `2024.11.0` milestone, meaning this should (hopefully) be fixed in the next release of home assistant.
> 
> 
> 
> I installed the new release today, reinstalled the integration and still no luck. I begin to think there is no solution to this.

They declined my fix.  I don't know what to say at this point, I'm quite annoyed with the HASS dev team.  I have a couple more ideas and past that point this project is pretty much dead.

Try the latest pre-release version; it attempts to install them separately.  If that doesn't work then I don't know what else to try.

**Comment by ngluvakov** [comment]
> > > Looks like they added it to the `2024.11.0` milestone, meaning this should (hopefully) be fixed in the next release of home assistant.
> > 
> > 
> > I installed the new release today, reinstalled the integration and still no luck. I begin to think there is no solution to this.
> 
> They declined my fix. I don't know what to say at this point, I'm quite annoyed with the HASS dev team. I have a couple more ideas and past that point this project is pretty much dead.
> 
> Try the latest pre-release version; it attempts to install them separately. If that doesn't work then I don't know what else to try.

Unfortunately, I tried the new, pre-release 1.1.17rc5...

**Comment by brtwrs** [comment]
Definitely not the cleanest option but what if you fork the beta package and take your own fork out of beta?

**Comment by msmitka** [comment]
Core: 2024.11.0
Supervisor: 2024.11.2
Operating System: 13.2
Frontend: 20241106.0
Miner: v1.1.17rc5
so i managed to install i just had to use like this:
first login to docker
`docker exec -it homeassistant bash`
and run in docker
`pip install --root-user-action=ignore pyasic==0.62.1`
after this install it works

**Comment by Schnitzel** [comment]
> > How come there is no workaround for a standalone installation similar to the docker variant?
> 
> There should be, just run those same commands in the `Terminal & SSH` plugin that you used when installing HACS.

I don't think that works as the Terminal of HACS, as it is sandboxed and can't change actual stuff of HomeAssistant itself.

**Comment by eriknylund** [comment]
> > > How come there is no workaround for a standalone installation similar to the docker variant?
> > 
> > 
> > There should be, just run those same commands in the `Terminal & SSH` plugin that you used when installing HACS.
> 
> I don't think that works as the Terminal of HACS, as it is sandboxed and can't change actual stuff of HomeAssistant itself.

Can confirm I've tried that approach and it doesn't work. Otherwise that would have been an easy workaround.

**Comment by b-rowan** [comment]
I FIXED IT!!!!!

All it took was taking my PR that was supposed to fix it, creating a `patch.py` file, copying my install function that doesnt suck, then every time I try to use pyasic, if it cant be found, it will just install it.  Thanks a lot to the absolutely garbage support from the home assistant team.

**Comment by b-rowan** [comment]
Fixed in 1.1.17.

**Comment by ngluvakov** [comment]
> I FIXED IT!!!!!
> 
> All it took was taking my PR that was supposed to fix it, creating a `patch.py` file, copying my install function that doesnt suck, then every time I try to use pyasic, if it cant be found, it will just install it. Thanks a lot to the absolutely garbage support from the home assistant team.

I knew it! Your personality trait won't allow you to accept that it's not doable. No project will ever die as long as there are people like you. 

Big thank you from Serbia.

**Comment by splice-next** [comment]
Woho! Good job @b-rowan 🙌 confirmed working on 2024.11.0 and 2024.10.4 both standalone versions. My spot price miners say thank you! 🙏 ❤️

**Comment by dennisreimann** [comment]
Can confirm it works with latest Home Assistant now. Thanks @b-rowan for hanging in and fixing this. I can imagine it has been a frustrating ride, glad you found an approach that works and doesn't depend on upstream changes. 🎉

**Comment by TuborgGold** [comment]
Nice work mate =) Awesome!
